name: Unit tests

on: [push]

jobs:

  windows:

    runs-on: windows-latest
    
    defaults:
        run:
            working-directory: ./CorgEng.Core

    steps:
      - uses: actions/checkout@v2
      - uses: openrndr/setup-opengl@v1.1
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: Nuget Restore Packages
        run: nuget restore CorgEng.Core.sln
        
      - name: Build Solution
        run: |
          msbuild.exe CorgEng.Core.sln /p:platform="ARM32" /p:configuration="Release"
        
      - name: Run Tests
        run: vstest.console.exe ..\CorgEng.Tests\bin\Release\CorgEng.Tests.dll
